backend/controllers/SiteController.php
<?php

namespace backend\controllers;

use yii\filters\VerbFilter;
use yii\web\Controller;

/**
 * Site controller.
 */
class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'demo' => [
                'class' => 'yii\web\ViewAction',
            ],
        ];
    }

    public function actionIndex()
    {
        $this->layout = false;
        return $this->render('index');
    }

    public function actionDashboard()
    {
        return $this->render('dashboard');
    }
}

frontend/controllers/SiteController.php
<?php

namespace frontend\controllers;

use common\models\Category;
use common\models\Article;
use common\models\Tag;
use frontend\services\TagService;
use Yii;
use yii\data\ActiveDataProvider;
use yii\helpers\Url;
use yii\web\Controller;

/**
 * Site controller.
 */
class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            [
                'class' => 'yii\filters\PageCache',
                'only' => ['sitemap'],
                'duration' => 60 * 60,
                'variations' => [
                    \Yii::$app->language,
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ]
        ];
    }

    /**
     * Displays homepage.
     *
     * @return mixed
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Article::find()->published(),
            'sort' => [
                'defaultOrder' => [
                    'is_top' => SORT_DESC,
                    'published_at' => SORT_DESC
                ]
            ]
        ]);
        $categories = Category::find()->orderBy('sort asc')->all();
        $hotTags = TagService::hot();
        return $this->render('index', [
            'dataProvider' => $dataProvider,
            'categories' => $categories,
            'hotTags' => $hotTags
        ]);
    }

    /**
     * 网站地图，百度搜索引擎爬虫用.
     *
     * @return array
     */
    public function actionSitemap()
    {
        \Yii::$app->response->format = \yii\web\Response::FORMAT_XML;
        \Yii::$container->set('yii\web\XmlResponseFormatter', ['rootTag' => 'urlset', 'itemTag' => 'url']);
        $urls = [];
        $models = Article::find()->published()->select('id')->orderBy(['id' => SORT_DESC])->each(20);
        foreach ($models as $model) {
            $url = [];
            $url['loc'] = Url::to(['/article/view', 'id' => $model->id], true);
            $urls[] = $url;
        }

        return $urls;
    }
}

backend/views/site/content.php
<div class="content-wrapper">
    <div id="tab-nav" class="tab-nav hidden-xs">
        <div class="tab-nav-wp">
            <ul id="min_title_list" class="acrossTab cl">
                <li class="active"><span data-href="<?= \yii\helpers\Url::to(['/site/dashboard']) ?>">控制面板</span><i></i><em></em></li>
            </ul>
        </div>
        <div class="tab-nav-more btn-group">
            <a id="js-tabNav-prev" class="btn radius btn-default size-S" href="javascript:;">
                <i class="fa fa-arrow-left"></i>
            </a>
            <a id="js-tabNav-next" class="btn radius btn-default size-S" href="javascript:;">
                <i class="fa fa-arrow-right"></i>
            </a>
        </div>
    </div>
    <div id="iframe_box" class="content-iframe">
        <div class="show_iframe">
            <div style="display:none" class="loading"></div>
            <iframe scrolling="yes" frameborder="0" src="<?= \yii\helpers\Url::to(['/site/dashboard']) ?>"></iframe>
        </div>
    </div>
</div>
<div id="context-menu">
    <ul class="dropdown-menu" role="menu">
        <li><a tabindex="-1" href="javascript:;">关闭</a></li>
        <li><a tabindex="-1" href="javascript:;">关闭其他</a></li>
        <li><a tabindex="-1" href="javascript:;">关闭全部</a></li>
    </ul>
</div>

backend/views/site/dashboard.php
<?php

/* @var $this yii\web\View */
use yii\helpers\Url;

$this->title = '控制面板';
?>
<div class="site-index">

    <div class="jumbotron">
        <div class="row">
            <div class="col-md-3 col-xs-6">
                <!-- small box -->
                <div class="small-box bg-green">
                    <div class="inner">
                        <h3><?= \common\models\Article::find()->count() ?><sup style="font-size: 20px">篇</sup></h3>
                        <p>当前内容(文章)</p>
                    </div>
                    <div class="icon">
                        <i class="fa fa-book"></i>
                    </div>
                    <a href="<?= Url::to(['/article/index']) ?>" class="small-box-footer" target="_blank">更多信息 <i class="fa fa-arrow-circle-right"></i></a>
                </div>
            </div><!-- ./col -->
            <div class="col-md-3 col-xs-6">
                <!-- small box -->
                <div class="small-box bg-red">
                    <div class="inner">
                        <h3><?= \common\models\Article::find()->pending()->count() ?><sup style="font-size: 20px">篇</sup></h3>
                        <p>待审内容(文章)</p>
                    </div>
                    <div class="icon">
                        <i class="fa fa-book"></i>
                    </div>
                    <a href="<?= Url::to(['/article/index']) ?>" class="small-box-footer" target="_blank">更多信息 <i class="fa fa-arrow-circle-right"></i></a>
                </div>
            </div><!-- ./col -->
            <div class="col-md-3 col-xs-6">
                <!-- small box -->
                <div class="small-box bg-yellow">
                    <div class="inner">
                        <h3><?= \common\modules\user\models\User::find()->count() ?><sup style="font-size: 20px">人</sup></h3>
                        <p>注册用户</p>
                    </div>
                    <div class="icon">
                        <i class="fa fa-user"></i>
                    </div>
                    <a href="<?= Url::to(['/user/default/index']) ?>" class="small-box-footer" target="_blank">更多信息 <i class="fa fa-arrow-circle-right"></i></a>
                </div>
            </div><!-- ./col -->
            <div class="col-md-3 col-xs-6">
                <!-- small box -->
                <div class="small-box bg-purple">
                    <div class="inner">
                        <h3><?= \common\models\Suggest::find()->count() ?></h3>
                        <p>留言</p>
                    </div>
                    <div class="icon">
                        <i class="fa fa-files-o"></i>
                    </div>
                    <a href="<?= Url::to(['/suggest/index']) ?>" class="small-box-footer" target="_blank">更多信息 <i class="fa fa-arrow-circle-right"></i></a>
                </div>
            </div><!-- ./col -->
        </div><!-- /.row -->
    </div>

</div>

backend/views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <a href="javascript:;" class="btn btn-primary btn-flat" onclick="history.back()">返回</a>
</div>

backend/views/site/header.php
<?php
use rbac\components\MenuHelper;
use yii\helpers\Html;
use yii\helpers\Url;

/* @var $this \yii\web\View */
/* @var $content string */

$logCount = \backend\models\SystemLog::find()->count();
$menuGroups = MenuHelper::getAssignedMenu(Yii::$app->user->id, null, function ($menu){
    return [
        'id' => $menu['id'],
        'name' => $menu['name'],
        'icon' => $menu['icon'],
    ];
});
?>

<header class="main-header">

    <?= Html::a('<span class="logo-mini">APP</span><span class="logo-lg">' . Yii::$app->config->get('site_name') . '</span>', Yii::$app->homeUrl, ['class' => 'logo']) ?>

    <nav class="navbar navbar-static-top" role="navigation">

        <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
            <span class="sr-only">Toggle navigation</span>
        </a>

        <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">
                <li><?= Html::a('<i class="fa fa-home"></i>', Yii::$app->config->get('SITE_URL'), ['target' => '_blank', 'data-not-iframe' => '1']) ?></li>
                <li id="log-dropdown" class="dropdown notifications-menu">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <i class="fa fa-warning"></i>
                        <?php if($logCount > 0) : ?>
                            <span class="label label-danger">
                                <?= $logCount ?>
                            </span>
                        <?php endif; ?>
                    </a>
                    <ul class="dropdown-menu">
                        <li class="header">
                            <?= sprintf('你有%d条日志', $logCount) ?>
                        </li>
                        <li>
                            <!-- inner menu: contains the actual data -->
                            <ul class="menu">
                                <?php foreach(\backend\models\SystemLog::find()->orderBy(['log_time'=>SORT_DESC])->limit(5)->all() as $logEntry): ?>
                                    <li>
                                        <a href="<?= Url::to(['/log/view', 'id'=>$logEntry->id]) ?>" target="_blank" title="错误日志">
                                            <i class="fa fa-warning <?= $logEntry->level == \yii\log\Logger::LEVEL_ERROR ? 'text-red' : 'text-yellow' ?>"></i>
                                            <?= $logEntry->category ?>
                                        </a>
                                    </li>
                                <?php endforeach; ?>
                            </ul>
                        </li>
                        <li class="footer">
                            <?= Html::a('查看全部', ['/log/index'], ['target' => '_blank', 'title' => '错误日志']) ?>
                        </li>
                    </ul>
                </li>
                <li class="dropdown user user-menu">
                    <a href="#"
                                                       class="dropdown-toggle" data-toggle="dropdown"> <img
                            src="<?= Yii::$app->user->identity->getAvatar(96) ;?>" class="user-image"
                            alt="User Image" /> <span class="hidden-xs"><?= Yii::$app->user->identity->username ?></span>
                    </a>
                    <ul class="dropdown-menu">
                        <!-- User image -->
                        <li class="user-header"><img
                                src="<?=  Yii::$app->user->identity->getAvatar(96) ;?>" class="img-circle"
                                alt="User Image" />

                            <p>
                                <?= Yii::$app->user->identity->username ?> - <?= current(Yii::$app->authManager->getRolesByUser(Yii::$app->user->id))->name ?>
                                <small>注册时间:<?= Yii::$app->formatter->asDate(Yii::$app->user->identity->created_at) ?></small>
                            </p></li>

                        <!-- Menu Footer-->
                        <li class="user-footer">
                            <div class="pull-left">
                                <?= Html::a('修改密码', ['/user/default/reset-password', 'id' => Yii::$app->user->id], ['class' => 'btn btn-default btn-flat', 'target' => '_blank', 'title' => '修改密码'])?>
                            </div>
                            <div class="pull-right">
                                <?= Html::a('登出', ['/user/default/logout' ], ['data-method' => 'post', 'class' => 'btn btn-default btn-flat'])?>
                            </div>
                        </li>
                    </ul>
                </li>
                <li><?= Html::a('<i class="fa  fa-sign-out"></i>', ['/user/default/logout'], ['data-method' => 'post']) ?></li>
            </ul>
        </div>
        <div class="navbar-header">
            <button class="btn btn-default  btn-sm navbar-toggle collapsed"
                    type="button" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="caret"></span>
            </button>
        </div>

        <div class="navbar-collapse collapse" role="navigation">
            <ul class="navbar-nav nav">
                <?php foreach ($menuGroups as $key => $menuGroup) : ?>
                    <li <?php if ($key == 0) {echo 'class="active"';} ?>><a href="#menu-group-<?= $menuGroup['id'] ?> " data-toggle="tab"><?= Html::icon($menuGroup['icon']) ?> <?= $menuGroup['name'] ?></a></li>
                <?php endforeach; ?>
            </ul>
        </div>
    </nav>
</header>
<aside class="main-sidebar">
    <section class="sidebar">
        <div class="tab-content">

        <?php foreach ($menuGroups as $key => $menuGroup): ?>
        <div class="tab-pane <?php if ($key == 0) {echo 'active';} ?>" id="menu-group-<?= $menuGroup['id'] ?>">
            <?= \backend\widgets\Menu::widget([
                'options' => ['class' => 'sidebar-menu'],
                'items' => MenuHelper::getAssignedMenu(Yii::$app->user->id, $menuGroup['id'])
            ]) ?>
        </div>
        <?php endforeach; ?>

        </div>
    </section>
</aside>

backend/views/site/index.php
<?php
use rbac\components\MenuHelper;
use rbac\models\Menu;
use yii\helpers\Html;

/* @var $this \yii\web\View */
/* @var $content string */
/* @var $context \yii\web\Controller */

backend\assets\ContextAsset::register($this);
\backend\assets\IframeAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Yii::$app->config->get('site_name') ?>管理后台</title>
    <?php $this->head() ?>
</head>
<body class="hold-transition <?= Yii::$app->config->get('backend_skin', 'skin-green') ?> sidebar-mini fixed">
<?php $this->beginBody() ?>
<div class="wrapper">

    <?= $this->render('header.php') ?>

    <?= $this->render('content.php') ?>

</div>
<?php $this->endBody() ?>
<?php if (isset($this->blocks['js'])): ?>
    <?= $this->blocks['js'] ?>
<?php endif; ?>
</body>
</html>
<?php $this->endPage() ?>